/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.mike.ui;

import dev.mike.core.search.Integration;
import dev.mike.core.search.ObjectService;
import dev.mike.core.search.Summer;
import dev.mike.infrastructure.tool.Browser;

import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.Serializable;

/**
 *
 * @author Usuario
 */
public class Card extends javax.swing.JPanel implements Serializable{
    
    private final Summer summer;
    private final BoardAction boardAction;

    /**
     * Creates new form Card
     */
    public Card(Summer summer, BoardAction boardAction) {
        initComponents();
        this.summer = summer;
        
        ObjectService objectService = summer.getObjectService();
        lblObjectName.setText(objectService.getName());
        if (!objectService.getPreprocessors().isEmpty()) {
            objectService.getPreprocessors().forEach(processor -> this.panelPreProcessorObject.add(createLabelProcessor(processor)));
        }
        if (!objectService.getPostprocessors().isEmpty()) {
            objectService.getPostprocessors().forEach(processor -> this.panelPosProcessorObject.add(createLabelProcessor(processor)));
        }
        Integration integration = summer.getIntegration();
        if (integration.getClassName() == null) {
            lblIntegration.setText(integration.getName());
            btnIntegrationClass.setVisible(false);
        } else {
            String[] classNames = integration.getClassName().split("\\.");
            lblIntegration.setText(integration.getName() + " (..." + classNames[classNames.length - 1] + ")");
        }
        if (!integration.getPreprocessors().isEmpty()) {
            integration.getPreprocessors().forEach(processor -> this.panelPreProcessorIntegration.add(createLabelProcessor(processor)));
        }
        if (!integration.getPostprocessors().isEmpty()) {
            integration.getPostprocessors().forEach(processor -> this.panelPosProcessorIntegration.add(createLabelProcessor(processor)));
        }
        
        this.repaint();
        this.boardAction = boardAction;
    }
    
    private JLabel createLabelProcessor(String value) {
        JLabel label = new JLabel("<html><p style=\"width:420px\">" + value + "</p></html>");
        Border borderExistente = label.getBorder();
        Border margen = new EmptyBorder(2, 5, 2, 5);
        label.setBorder(new CompoundBorder(borderExistente, margen));
        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                boardAction.openClassName(value);
            }
        });
        
        return label;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblObjectName = new javax.swing.JLabel();
        panelPreProcessorObject = new javax.swing.JPanel();
        panelPosProcessorObject = new javax.swing.JPanel();
        lblIntegration = new javax.swing.JLabel();
        panelPreProcessorIntegration = new javax.swing.JPanel();
        panelPosProcessorIntegration = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnObjectFabric = new javax.swing.JButton();
        btnIntegrationClass = new javax.swing.JButton();
        btnIntegrationFabric = new javax.swing.JButton();
        lblRemove = new javax.swing.JLabel();

        setBackground(new java.awt.Color(232, 232, 232));

        lblObjectName.setText("Object Name");

        panelPreProcessorObject.setBackground(new java.awt.Color(255, 255, 255));
        panelPreProcessorObject.setName(""); // NOI18N
        panelPreProcessorObject.setPreferredSize(new java.awt.Dimension(400, 20));
        panelPreProcessorObject.setLayout(new javax.swing.BoxLayout(panelPreProcessorObject, javax.swing.BoxLayout.Y_AXIS));

        panelPosProcessorObject.setBackground(new java.awt.Color(255, 255, 255));
        panelPosProcessorObject.setPreferredSize(new java.awt.Dimension(400, 20));
        panelPosProcessorObject.setLayout(new javax.swing.BoxLayout(panelPosProcessorObject, javax.swing.BoxLayout.Y_AXIS));

        lblIntegration.setText("Integration Name");
        lblIntegration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIntegrationMouseClicked(evt);
            }
        });

        panelPreProcessorIntegration.setBackground(new java.awt.Color(255, 255, 255));
        panelPreProcessorIntegration.setPreferredSize(new java.awt.Dimension(400, 20));
        panelPreProcessorIntegration.setLayout(new javax.swing.BoxLayout(panelPreProcessorIntegration, javax.swing.BoxLayout.Y_AXIS));

        panelPosProcessorIntegration.setBackground(new java.awt.Color(255, 255, 255));
        panelPosProcessorIntegration.setPreferredSize(new java.awt.Dimension(400, 20));
        panelPosProcessorIntegration.setLayout(new javax.swing.BoxLayout(panelPosProcessorIntegration, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Pre-Processor");

        jLabel2.setText("Post-Processor");

        jLabel3.setText("Pre-Processor");

        jLabel4.setText("Post-Processor");

        btnObjectFabric.setText("Fabric");
        btnObjectFabric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObjectFabricActionPerformed(evt);
            }
        });

        btnIntegrationClass.setText("Class");
        btnIntegrationClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntegrationClassActionPerformed(evt);
            }
        });

        btnIntegrationFabric.setText("Fabric");
        btnIntegrationFabric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntegrationFabricActionPerformed(evt);
            }
        });

        lblRemove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRemove.setText("Remove");
        lblRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelPreProcessorObject, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelPosProcessorObject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelPosProcessorIntegration, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelPreProcessorIntegration, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnIntegrationClass)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnIntegrationFabric))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnObjectFabric)
                                        .addComponent(jLabel1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblObjectName)
                                    .addComponent(lblIntegration))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblRemove)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRemove)
                .addGap(3, 3, 3)
                .addComponent(lblObjectName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObjectFabric, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPreProcessorObject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPosProcessorObject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblIntegration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntegrationFabric, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntegrationClass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(panelPreProcessorIntegration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPosProcessorIntegration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblIntegrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIntegrationMouseClicked

    }//GEN-LAST:event_lblIntegrationMouseClicked

    private void btnObjectFabricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObjectFabricActionPerformed
        Browser.openUrl(summer.getObjectService().getLink());        // TODO add your handling code here:
    }//GEN-LAST:event_btnObjectFabricActionPerformed

    private void btnIntegrationFabricActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntegrationFabricActionPerformed
        Browser.openUrl(summer.getIntegration().getLink());
    }//GEN-LAST:event_btnIntegrationFabricActionPerformed

    private void btnIntegrationClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntegrationClassActionPerformed
        boardAction.openClassName(summer.getIntegration().getClassName());
    }//GEN-LAST:event_btnIntegrationClassActionPerformed

    private void lblRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseClicked
        boardAction.removeCard(this);
    }//GEN-LAST:event_lblRemoveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntegrationClass;
    private javax.swing.JButton btnIntegrationFabric;
    private javax.swing.JButton btnObjectFabric;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblIntegration;
    private javax.swing.JLabel lblObjectName;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JPanel panelPosProcessorIntegration;
    private javax.swing.JPanel panelPosProcessorObject;
    private javax.swing.JPanel panelPreProcessorIntegration;
    private javax.swing.JPanel panelPreProcessorObject;
    // End of variables declaration//GEN-END:variables
}
